name: Terraform CI/CD v3

on:
  workflow_dispatch:
  
  push:
    branches:
      - dev
    paths:
      - terraform/**
  pull_request:
    branches:
      - dev

env:
  TF_VERSION: "1.5.7"
  TF_ROOT: ./terraform
  TF_LOG: INFO
  ENVIRONMENT: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
  AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  set-environment: #this is a job named 'set-environment'
    runs-on: ubuntu-latest #your preferred OS
    outputs: #the env value needs to be exposed as an output in order to be reached from other jobs
      current_env: ${{ steps.set_env.outputs.current_env }} #output variable to store the relevant environment
    steps:
      - name: Check if prod
        if: endsWith(github.ref, '/main') #if the triggering branch is 'main'
        run: |
          echo "ENVIRONMENT_NAME=prod" >> $GITHUB_ENV #retrieve secrets from 'prod' environment in Github
      - name: Check if dev
        if: endsWith(github.ref, '/dev') #if the triggering branch is 'dev'
        run: |
          echo "ENVIRONMENT_NAME=dev" >> $GITHUB_ENV #retrieve secrets from 'dev' environment in Github
      - name: Set output
        id: set_env
        run: echo "::set-output name=current_env::${{ env.ENVIRONMENT_NAME }}"

  terraform:
   name: "Terraform Infrastructure Change Management"
   runs-on: ubuntu-latest
   needs: set-environment 
   environment: ${{ needs.set-environment.outputs.current_env }}
   defaults:
     run:
       shell: bash
       working-directory: ${{ env.TF_ROOT }}
 
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v4
      
     - name: Configurar credenciales de AWS
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ env.AWS_REGION }}
 
     - name: Mostrar entorno actual
       run: echo "Desplegando en el ambiente:"

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: ${{ env.TF_VERSION }}
    
     - name: Terraform init
       id: init
       run: terraform init -backend-config="bucket=$TF_BUCKET_STATE"
 
     - name: Terraform format
       id: fmt
       run: terraform fmt -check
    
     - name: Terraform validate
       id: validate
       run: terraform validate
